// Repository List Actions
export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS";
export const GET_REPOSITORIES_ERROR = "GET_REPOSITORIES_ERROR";

// Repository Details Actions
export const SELECT_REPOSITORY = "SELECT_REPOSITORY";
export const GET_REPOSITORY = "GET_REPOSITORY";
export const GET_REPOSITORY_SUCCESS = "GET_REPOSITORY_SUCCESS";
export const GET_REPOSITORY_ERROR = "GET_REPOSITORY_ERROR";