// Repository List Actions
export const GET_REPOSITORIES = "GET_REPOSITORIES";
export const GET_REPOSITORIES_SUCCESS = "GET_REPOSITORIES_SUCCESS";
export const GET_REPOSITORIES_ERROR = "GET_REPOSITORIES_ERROR";

// Repository Details Actions
export const SELECT_REPOSITORY = "SELECT_REPOSITORY";

// Repository Contributors
export const GET_CONTRIBUTORS = "GET_CONTRIBUTORS";
export const LOAD_MORE_CONTRIBUTORS = "LOAD_MORE_CONTRIBUTORS";
export const GET_CONTRIBUTORS_SUCCESS = "GET_CONTRIBUTORS_SUCCESS";
export const GET_CONTRIBUTORS_ERROR = "GET_CONTRIBUTORS_ERROR";
export const LOAD_MORE_CONTRIBUTORS_SUCCESS = "LOAD_MORE_CONTRIBUTORS_SUCCESS";
export const LOAD_MORE_CONTRIBUTORS_ERROR = "LOAD_MORE_CONTRIBUTORS_ERROR";
